command:
- streamlit
- run
- app.py
env:
- name: DATABRICKS_WAREHOUSE_ID
  valueFrom: sql-warehouse
- name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
  value: 'false'
- name: TABLE_NAME
  value: jack_demos.iop_schema.gold_iop_features_version_demo
- name: FE_ENDPOINT_NAME
  value: iop_schema-fe_model-serving-endpoint
- name: SI_ENDPOINT_NAME
  value: iop_schema-si_model-serving-endpoint
